require('dotenv').config();

const mongoose = require('mongoose');

const Food = require('./models/Food');

const afghanFoods = [
  {
    name: 'Kabuli Pulao',
    description: 'Afghanistan’s national rice dish with tender meat, carrots, raisins, almonds, and fragrant spices.',
    category: 'Rice',
    price: 350,
    imageUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b',
    availability: true,
    cuisine: 'Afghan',
    spiceLevel: 'Medium',
    prepTime: 45,
    calories: 650,
    isFeatured: true,
    isTrending: true,
  },
  {
    name: 'Mantu',
    description: 'Steamed Afghan dumplings filled with minced meat and onions, topped with yogurt and lentil sauce.',
    category: 'Dumplings',
    price: 280,
    imageUrl: 'https://images.unsplash.com/photo-1496116218417-1a781b1c416c',
    availability: true,
    cuisine: 'Afghan',
    spiceLevel: 'Medium',
    prepTime: 50,
    calories: 520,
    isFeatured: true,
    isTrending: true,
  },
  {
    name: 'Ashak',
    description: 'Afghan leek dumplings served with garlic yogurt and rich tomato meat sauce.',
    category: 'Dumplings',
    price: 260,
    imageUrl: 'https://images.unsplash.com/photo-1495521821757-a1efb6729352',
    availability: true,
    cuisine: 'Afghan',
    spiceLevel: 'Medium',
    prepTime: 55,
    calories: 480,
    isFeatured: true,
    isTrending: false,
  },
  {
    name: 'Bolani Kachalu',
    description: 'Crispy Afghan flatbread stuffed with seasoned potatoes and herbs.',
    category: 'Bread',
    price: 120,
    imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950',
    availability: true,
    cuisine: 'Afghan',
    spiceLevel: 'Mild',
    prepTime: 25,
    calories: 310,
    isFeatured: false,
    isTrending: true,
  },
  {
    name: 'Bolani Gandana',
    description: 'Traditional Afghan flatbread filled with leeks, herbs, and light spices.',
    category: 'Bread',
    price: 130,
    imageUrl: 'https://images.unsplash.com/photo-1627308595229-7830a5c91f9f',
    availability: true,
    cuisine: 'Afghan',
    spiceLevel: 'Mild',
    prepTime: 25,
    calories: 295,
    isFeatured: false,
    isTrending: false,
  },
  {
    name: 'Chapli Kebab',
    description: 'Spiced ground meat kebab shaped into patties and fried until crispy and flavorful.',
    category: 'Kebab',
    price: 220,
    imageUrl: 'https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba',
    availability: true,
    cuisine: 'Afghan',
    spiceLevel: 'Spicy',
    prepTime: 30,
    calories: 540,
    isFeatured: true,
    isTrending: true,
  },
  {
    name: 'Seekh Kebab',
    description: 'Juicy minced meat kebabs grilled on skewers with Afghan spices.',
    category: 'Kebab',
    price: 300,
    imageUrl: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0',
    availability: true,
    cuisine: 'Afghan',
    spiceLevel: 'Medium',
    prepTime: 35,
    calories: 560,
    isFeatured: true,
    isTrending: false,
  },
  {
    name: 'Tikka Kebab',
    description: 'Tender marinated meat cubes grilled over flame and served with naan.',
    category: 'Kebab',
    price: 340,
    imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1',
    availability: true,
    cuisine: 'Afghan',
    spiceLevel: 'Medium',
    prepTime: 35,
    calories: 590,
    isFeatured: false,
    isTrending: true,
  },
  {
    name: 'Shami Kebab',
    description: 'Soft minced meat patties made with lentils, herbs, and Afghan spices.',
    category: 'Kebab',
    price: 210,
    imageUrl: 'https://images.unsplash.com/photo-1625944525533-473f1a3d54e7',
    availability: true,
    cuisine: 'Afghan',
    spiceLevel: 'Medium',
    prepTime: 40,
    calories: 470,
    isFeatured: false,
    isTrending: false,
  },
  {
    name: 'Qorma Sabzi',
    description: 'Rich Afghan spinach stew cooked with herbs, meat, and aromatic spices.',
    category: 'Qorma',
    price: 250,
    imageUrl: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d',
    availability: true,
    cuisine: 'Afghan',
    spiceLevel: 'Medium',
    prepTime: 45,
    calories: 430,
    isFeatured: false,
    isTrending: false,
  },
  {
    name: 'Qorma Lawand',
    description: 'Creamy Afghan chicken curry cooked with yogurt, spices, and herbs.',
    category: 'Qorma',
    price: 290,
    imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641',
    availability: true,
    cuisine: 'Afghan',
    spiceLevel: 'Medium',
    prepTime: 40,
    calories: 560,
    isFeatured: true,
    isTrending: false,
  },
  {
    name: 'Qorma Nakhod',
    description: 'Traditional chickpea curry cooked with Afghan spices and tomato base.',
    category: 'Qorma',
    price: 180,
    imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d',
    availability: true,
    cuisine: 'Afghan',
    spiceLevel: 'Mild',
    prepTime: 35,
    calories: 390,
    isFeatured: false,
    isTrending: false,
  },
  {
    name: 'Qorma Kofta',
    description: 'Afghan meatball curry cooked in a rich tomato and onion sauce.',
    category: 'Qorma',
    price: 270,
    imageUrl: 'https://images.unsplash.com/photo-1604909052743-94e838986d24',
    availability: true,
    cuisine: 'Afghan',
    spiceLevel: 'Medium',
    prepTime: 45,
    calories: 530,
    isFeatured: false,
    isTrending: true,
  },
  {
    name: 'Shorwa',
    description: 'Traditional Afghan meat soup with potatoes, chickpeas, vegetables, and herbs.',
    category: 'Soup',
    price: 230,
    imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd',
    availability: true,
    cuisine: 'Afghan',
    spiceLevel: 'Mild',
    prepTime: 50,
    calories: 420,
    isFeatured: false,
    isTrending: false,
  },
  {
    name: 'Aush',
    description: 'Afghan noodle soup with beans, herbs, yogurt, and meat sauce topping.',
    category: 'Soup',
    price: 200,
    imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624',
    availability: true,
    cuisine: 'Afghan',
    spiceLevel: 'Medium',
    prepTime: 45,
    calories: 440,
    isFeatured: true,
    isTrending: false,
  },
  {
    name: 'Mashawa',
    description: 'Hearty Afghan soup made with mung beans, rice, meat, yogurt, and herbs.',
    category: 'Soup',
    price: 210,
    imageUrl: 'https://images.unsplash.com/photo-1603105037880-880cd4edfb0d',
    availability: true,
    cuisine: 'Afghan',
    spiceLevel: 'Mild',
    prepTime: 50,
    calories: 450,
    isFeatured: false,
    isTrending: false,
  },
  {
    name: 'Afghan Naan',
    description: 'Traditional Afghan flatbread baked until soft, golden, and slightly crisp.',
    category: 'Bread',
    price: 40,
    imageUrl: 'https://images.unsplash.com/photo-1586444248902-2f64eddc13df',
    availability: true,
    cuisine: 'Afghan',
    spiceLevel: 'Mild',
    prepTime: 15,
    calories: 220,
    isFeatured: false,
    isTrending: false,
  },
  {
    name: 'Roghani Naan',
    description: 'Soft enriched Afghan bread with oil, sesame, and a rich golden surface.',
    category: 'Bread',
    price: 70,
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff',
    availability: true,
    cuisine: 'Afghan',
    spiceLevel: 'Mild',
    prepTime: 20,
    calories: 280,
    isFeatured: false,
    isTrending: true,
  },
  {
    name: 'Sheermaal',
    description: 'Sweet, soft Afghan milk bread flavored with cardamom and baked golden.',
    category: 'Bread',
    price: 90,
    imageUrl: 'https://images.unsplash.com/photo-1608198093002-ad4e005484ec',
    availability: true,
    cuisine: 'Afghan',
    spiceLevel: 'Mild',
    prepTime: 25,
    calories: 300,
    isFeatured: false,
    isTrending: false,
  },
  {
    name: 'Borani Banjan',
    description: 'Fried eggplant layered with tomato sauce and garlic yogurt topping.',
    category: 'Vegetarian',
    price: 190,
    imageUrl: 'https://images.unsplash.com/photo-1604908177522-402a7f7fbf08',
    availability: true,
    cuisine: 'Afghan',
    spiceLevel: 'Medium',
    prepTime: 35,
    calories: 370,
    isFeatured: true,
    isTrending: true,
  },
  {
    name: 'Borani Kadoo',
    description: 'Sweet and savory pumpkin dish served with garlic yogurt and meat sauce.',
    category: 'Vegetarian',
    price: 180,
    imageUrl: 'https://images.unsplash.com/photo-1509358271058-acd22cc93898',
    availability: true,
    cuisine: 'Afghan',
    spiceLevel: 'Mild',
    prepTime: 35,
    calories: 330,
    isFeatured: true,
    isTrending: false,
  },
  {
    name: 'Badenjan Chalaw',
    description: 'Eggplant stew served with Afghan rice and rich tomato sauce.',
    category: 'Rice',
    price: 240,
    imageUrl: 'https://images.unsplash.com/photo-1604908177453-7462950a6a3b',
    availability: true,
    cuisine: 'Afghan',
    spiceLevel: 'Medium',
    prepTime: 40,
    calories: 510,
    isFeatured: false,
    isTrending: false,
  },
  {
    name: 'Chalaw',
    description: 'Simple Afghan white rice served as a classic side with qorma and kebabs.',
    category: 'Rice',
    price: 120,
    imageUrl: 'https://images.unsplash.com/photo-1512058564366-18510be2db19',
    availability: true,
    cuisine: 'Afghan',
    spiceLevel: 'Mild',
    prepTime: 25,
    calories: 330,
    isFeatured: false,
    isTrending: false,
  },
  {
    name: 'Qabuli Uzbeki',
    description: 'A regional pulao variation with rich spices, meat, carrots, raisins, and rice.',
    category: 'Rice',
    price: 370,
    imageUrl: 'https://images.unsplash.com/photo-1596797038530-2c107229654b',
    availability: true,
    cuisine: 'Afghan',
    spiceLevel: 'Medium',
    prepTime: 50,
    calories: 700,
    isFeatured: true,
    isTrending: true,
  },
  {
    name: 'Lamb Karahi',
    description: 'Afghan-style lamb cooked in a karahi with tomatoes, green chilies, and spices.',
    category: 'Meat',
    price: 420,
    imageUrl: 'https://images.unsplash.com/photo-1631292784640-2b24be784d5d',
    availability: true,
    cuisine: 'Afghan',
    spiceLevel: 'Spicy',
    prepTime: 45,
    calories: 690,
    isFeatured: true,
    isTrending: true,
  },
  {
    name: 'Chicken Karahi',
    description: 'Chicken cooked in a wok-style pan with tomatoes, garlic, chilies, and spices.',
    category: 'Meat',
    price: 330,
    imageUrl: 'https://images.unsplash.com/photo-1604908176997-4318f8fbb0cc',
    availability: true,
    cuisine: 'Afghan',
    spiceLevel: 'Spicy',
    prepTime: 40,
    calories: 590,
    isFeatured: false,
    isTrending: true,
  },
  {
    name: 'Afghan Lamb Chops',
    description: 'Juicy lamb chops marinated in Afghan spices and grilled to perfection.',
    category: 'Meat',
    price: 480,
    imageUrl: 'https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba',
    availability: true,
    cuisine: 'Afghan',
    spiceLevel: 'Medium',
    prepTime: 40,
    calories: 760,
    isFeatured: true,
    isTrending: false,
  },
  {
    name: 'Do Piaza',
    description: 'Traditional meat dish cooked with onions, chickpeas, and Afghan spices.',
    category: 'Meat',
    price: 310,
    imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641',
    availability: true,
    cuisine: 'Afghan',
    spiceLevel: 'Medium',
    prepTime: 45,
    calories: 600,
    isFeatured: false,
    isTrending: false,
  },
  {
    name: 'Afghan Kofta',
    description: 'Spiced Afghan meatballs served with tomato gravy and fresh herbs.',
    category: 'Meat',
    price: 270,
    imageUrl: 'https://images.unsplash.com/photo-1604909052743-94e838986d24',
    availability: true,
    cuisine: 'Afghan',
    spiceLevel: 'Medium',
    prepTime: 40,
    calories: 540,
    isFeatured: false,
    isTrending: true,
  },
  {
    name: 'Kichiri Quroot',
    description: 'Afghan rice and mung bean dish topped with dried yogurt sauce and meat.',
    category: 'Rice',
    price: 260,
    imageUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b',
    availability: true,
    cuisine: 'Afghan',
    spiceLevel: 'Medium',
    prepTime: 45,
    calories: 580,
    isFeatured: true,
    isTrending: false,
  },
  {
    name: 'Qurooti',
    description: 'Traditional Afghan bread dish soaked with quroot sauce and topped with meat.',
    category: 'Traditional',
    price: 250,
    imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950',
    availability: true,
    cuisine: 'Afghan',
    spiceLevel: 'Medium',
    prepTime: 35,
    calories: 520,
    isFeatured: false,
    isTrending: false,
  },
  {
    name: 'Shola',
    description: 'Soft Afghan rice dish cooked with meat, beans, and comforting spices.',
    category: 'Traditional',
    price: 230,
    imageUrl: 'https://images.unsplash.com/photo-1596797038530-2c107229654b',
    availability: true,
    cuisine: 'Afghan',
    spiceLevel: 'Mild',
    prepTime: 45,
    calories: 560,
    isFeatured: false,
    isTrending: false,
  },
  {
    name: 'Halwa',
    description: 'Sweet Afghan dessert made with flour, sugar, cardamom, and oil or butter.',
    category: 'Dessert',
    price: 100,
    imageUrl: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c',
    availability: true,
    cuisine: 'Afghan',
    spiceLevel: 'Mild',
    prepTime: 25,
    calories: 360,
    isFeatured: false,
    isTrending: true,
  },
  {
    name: 'Firni',
    description: 'Creamy Afghan milk pudding flavored with cardamom and topped with nuts.',
    category: 'Dessert',
    price: 120,
    imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777',
    availability: true,
    cuisine: 'Afghan',
    spiceLevel: 'Mild',
    prepTime: 25,
    calories: 290,
    isFeatured: true,
    isTrending: true,
  },
  {
    name: 'Sheer Yakh',
    description: 'Traditional Afghan ice cream flavored with cardamom, rosewater, and pistachio.',
    category: 'Dessert',
    price: 130,
    imageUrl: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb',
    availability: true,
    cuisine: 'Afghan',
    spiceLevel: 'Mild',
    prepTime: 20,
    calories: 320,
    isFeatured: true,
    isTrending: false,
  },
  {
    name: 'Jalebi',
    description: 'Crispy sweet spirals soaked in syrup, popular in Afghan sweet shops.',
    category: 'Dessert',
    price: 90,
    imageUrl: 'https://images.unsplash.com/photo-1605197161470-d0261cac6767',
    availability: true,
    cuisine: 'Afghan',
    spiceLevel: 'Mild',
    prepTime: 30,
    calories: 390,
    isFeatured: false,
    isTrending: true,
  },
  {
    name: 'Baklava Afghan Style',
    description: 'Layered pastry dessert filled with nuts and sweet syrup.',
    category: 'Dessert',
    price: 160,
    imageUrl: 'https://images.unsplash.com/photo-1519676867240-f03562e64548',
    availability: true,
    cuisine: 'Afghan',
    spiceLevel: 'Mild',
    prepTime: 35,
    calories: 430,
    isFeatured: false,
    isTrending: false,
  },
  {
    name: 'Dogh',
    description: 'Refreshing Afghan yogurt drink with mint and salt.',
    category: 'Drinks',
    price: 70,
    imageUrl: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc',
    availability: true,
    cuisine: 'Afghan',
    spiceLevel: 'Mild',
    prepTime: 5,
    calories: 120,
    isFeatured: false,
    isTrending: true,
  },
  {
    name: 'Afghan Green Tea',
    description: 'Traditional Afghan green tea served hot with cardamom or sugar.',
    category: 'Drinks',
    price: 40,
    imageUrl: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574',
    availability: true,
    cuisine: 'Afghan',
    spiceLevel: 'Mild',
    prepTime: 8,
    calories: 5,
    isFeatured: false,
    isTrending: false,
  },
  {
    name: 'Shir Chai',
    description: 'Milk tea with cardamom, sugar, and a creamy Afghan flavor.',
    category: 'Drinks',
    price: 60,
    imageUrl: 'https://images.unsplash.com/photo-1561336526-2914f13ceb36',
    availability: true,
    cuisine: 'Afghan',
    spiceLevel: 'Mild',
    prepTime: 10,
    calories: 160,
    isFeatured: false,
    isTrending: false,
  },
  {
    name: 'Qaymaq Chai',
    description: 'Tea served with rich Afghan clotted cream for a luxurious breakfast drink.',
    category: 'Drinks',
    price: 90,
    imageUrl: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3',
    availability: true,
    cuisine: 'Afghan',
    spiceLevel: 'Mild',
    prepTime: 12,
    calories: 220,
    isFeatured: true,
    isTrending: false,
  },
  {
    name: 'Afghan Breakfast Platter',
    description: 'Traditional breakfast with naan, eggs, qaymaq, cheese, honey, and tea.',
    category: 'Breakfast',
    price: 280,
    imageUrl: 'https://images.unsplash.com/photo-1533089860892-a7c6f0a88666',
    availability: true,
    cuisine: 'Afghan',
    spiceLevel: 'Mild',
    prepTime: 25,
    calories: 640,
    isFeatured: true,
    isTrending: true,
  },
  {
    name: 'Qaymaq with Naan',
    description: 'Fresh Afghan cream served with warm naan and honey.',
    category: 'Breakfast',
    price: 180,
    imageUrl: 'https://images.unsplash.com/photo-1495147466023-ac5c588e2e94',
    availability: true,
    cuisine: 'Afghan',
    spiceLevel: 'Mild',
    prepTime: 10,
    calories: 420,
    isFeatured: false,
    isTrending: false,
  },
  {
    name: 'Eggs with Tomato',
    description: 'Afghan-style eggs cooked with tomatoes, onions, and green chilies.',
    category: 'Breakfast',
    price: 160,
    imageUrl: 'https://images.unsplash.com/photo-1525351484163-7529414344d8',
    availability: true,
    cuisine: 'Afghan',
    spiceLevel: 'Medium',
    prepTime: 15,
    calories: 330,
    isFeatured: false,
    isTrending: false,
  },
  {
    name: 'Afghan Salad',
    description: 'Fresh salad with cucumber, tomato, onion, lemon, herbs, and light seasoning.',
    category: 'Salad',
    price: 90,
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999',
    availability: true,
    cuisine: 'Afghan',
    spiceLevel: 'Mild',
    prepTime: 10,
    calories: 110,
    isFeatured: false,
    isTrending: false,
  },
  {
    name: 'Pickled Vegetables',
    description: 'Tangy Afghan pickles served as a side with kebabs and rice dishes.',
    category: 'Side',
    price: 60,
    imageUrl: 'https://images.unsplash.com/photo-1625944525533-473f1a3d54e7',
    availability: true,
    cuisine: 'Afghan',
    spiceLevel: 'Spicy',
    prepTime: 5,
    calories: 80,
    isFeatured: false,
    isTrending: false,
  },
  {
    name: 'Lubya',
    description: 'Afghan red kidney bean stew cooked with tomato, onions, and spices.',
    category: 'Vegetarian',
    price: 170,
    imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d',
    availability: true,
    cuisine: 'Afghan',
    spiceLevel: 'Medium',
    prepTime: 35,
    calories: 390,
    isFeatured: false,
    isTrending: false,
  },
  {
    name: 'Dal Afghan Style',
    description: 'Lentils cooked with garlic, onions, tomatoes, and Afghan spices.',
    category: 'Vegetarian',
    price: 160,
    imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d',
    availability: true,
    cuisine: 'Afghan',
    spiceLevel: 'Medium',
    prepTime: 30,
    calories: 360,
    isFeatured: false,
    isTrending: false,
  },
  {
    name: 'Sambosa',
    description: 'Crispy fried pastry stuffed with spiced potatoes, meat, or lentils.',
    category: 'Snack',
    price: 80,
    imageUrl: 'https://images.unsplash.com/photo-1601050690117-94f5f6fa8bd7',
    availability: true,
    cuisine: 'Afghan',
    spiceLevel: 'Medium',
    prepTime: 20,
    calories: 260,
    isFeatured: false,
    isTrending: true,
  },
  {
    name: 'Pakora Afghan Style',
    description: 'Crispy fritters made with vegetables, gram flour, herbs, and spices.',
    category: 'Snack',
    price: 90,
    imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950',
    availability: true,
    cuisine: 'Afghan',
    spiceLevel: 'Spicy',
    prepTime: 20,
    calories: 290,
    isFeatured: false,
    isTrending: false,
  },
  {
    name: 'Afghan Burger',
    description: 'Street-style Afghan burger filled with egg, fries, salad, sauces, and kebab.',
    category: 'Street Food',
    price: 150,
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd',
    availability: true,
    cuisine: 'Afghan',
    spiceLevel: 'Medium',
    prepTime: 18,
    calories: 520,
    isFeatured: false,
    isTrending: true,
  },
];

const seedFoods = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);

    console.log('MongoDB Connected');

    await Food.deleteMany();

    await Food.insertMany(afghanFoods);

    console.log(`${afghanFoods.length} Afghan dishes inserted successfully`);

    process.exit();
  } catch (error) {
    console.log(error);

    process.exit(1);
  }
};

seedFoods();